const ActionType = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_ITEMS: "GET_ITEMS",
  GET_CATEGORIES: "GET_CATEGORIES",
  POST_ITEM: "POST_ITEM",
  POST_CATEGORY: "POST_CATEGORY",
  PUT_ITEM: "PUT_ITEM",
  PUT_CATEGORY: "PUT_CATEGORY",
  DELETE_ITEM: "DELETE_ITEM",
  DELETE_CATEGORY: "DELETE_CATEGORY",
};

export default ActionType;
